version: '3.7'
services:
  app001-frontend:
    container_name: app001-frontend
    build:
      context: application
      args:
        NODE_ENV: 'production'
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/vhosts:/etc/nginx/conf.d
      - ./docker/nginx/logs:/var/log/nginx
      - ./docker/nginx/ssl:/etc/nginx/ssl
      - ./docker/certbot-etc:/etc/letsencrypt
      - ./docker/certbot-var:/var/lib/letsencrypt
      - ./docker/dhparam:/etc/ssl/certs
      - /var/www/node_modules
      - .env:/var/www/application/.env:ro
    environment:
      DOMAIN: "localhost"
      NODE_ENV: "production"
      SERVER_PORT: "3010"
    links:
      - app001-backend:app001-backend
#      - app001-provider:app001-provider
    networks:
      - service-web
    restart: always
  app001-backend:
    container_name: app001-backend
    build:
      context: .
      args:
        NODE_ENV: 'production'
        SERVER_PORT: 3010
    ports:
      - 3010:3010
    networks:
      - service-web
    restart: always
    links:
      - app001-provider:app001-provider
      - app001-postgres:app001-postgres
    depends_on:
      - app001-provider
      - app001-postgres
    volumes:
      - ./docker/certbot-etc:/etc/letsencrypt
      - ./docker/certbot-var:/var/lib/letsencrypt
      - /server/node_modules
    env_file:
      - .env
  app001-provider:
    container_name:   app001-provider
    build:
      context: ./provider/.
      args:
        NODE_ENV: "production"
        PORT: 5555
    env_file:
      - .env
    ports:
      - 5555:5555
    networks:
      - service-web
    restart: always
    volumes:
      - .env:/go/src/provider/.env:ro
  app001-postgres:
    image: timescale/timescaledb:2.5.1-pg14
    container_name: app001-postgres
    environment:
      - POSTGRES_USER=services
      - POSTGRES_PASSWORD=services
      - POSTGRES_DB=services
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" , "-U", "trade" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - service-web
    volumes:
      - ./docker/postgresql/db:/var/lib/postgresql/data/pgdata
      - ./docker/postgresql:/etc/postgresql
  app001-migrator:
    links:
      - app001-postgres
    depends_on:
      - app001-postgres
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://services:services@app001-postgres:5432/services
    entrypoint: npm run migration:run
networks:
  service-web:
    name: service-web
    driver: bridge
