export const CREATE_ACCOUNT = 'CREATE_ACCOUNT'
export const GET_ACCOUNTS = 'GET_ACCOUNTS'
export const GET_ACCOUNT = 'GET_ACCOUNT'
export const REMOVE_ACCOUNT = 'REMOVE_ACCOUNT'

export const SET_ACCOUNT = 'SET_ACCOUNT'
export const SET_ACCOUNT_ENABLE = 'SET_ACCOUNT_ENABLE'
export const GET_ACCOUNT_SUCCESS = 'GET_ACCOUNT_SUCCESS'
export const GET_ACCOUNTS_SUCCESS = 'GET_ACCOUNTS_SUCCESS'
export const SET_ACCOUNT_SUCCESS = 'SET_ACCOUNT_SUCCESS'
export const SET_ACCOUNT_ERROR = 'SET_ACCOUNT_ERROR'
export const GET_ACCOUNT_ERROR = 'GET_ACCOUNT_ERROR'

export const GET_ACCOUNTS_ERROR = 'GET_ACCOUNTS_ERROR'

