export const CREATE_ROLE = 'CREATE_ROLE'
export const GET_ROLES = 'GET_ROLES'
export const GET_ROLE = 'GET_ROLE'
export const REMOVE_ROLE = 'REMOVE_ROLE'

export const SET_ROLE = 'SET_ROLE'
export const SET_ROLE_ENABLE = 'SET_ROLE_ENABLE'
export const GET_ROLE_SUCCESS = 'GET_ROLE_SUCCESS'
export const GET_ROLES_SUCCESS = 'GET_ROLES_SUCCESS'
export const SET_ROLE_SUCCESS = 'SET_ROLE_SUCCESS'
export const SET_ROLE_ERROR = 'SET_ROLE_ERROR'
export const GET_ROLE_ERROR = 'GET_ROLE_ERROR'

export const GET_ROLES_ERROR = 'GET_ROLES_ERROR'

